######################################################################
# Automatically generated by qmake (3.0) ? 12? 6 17:25:15 2020
######################################################################

TEMPLATE = app
TARGET = lab4
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += ButtonWindow.h
SOURCES += ButtonWindow.cpp
